"""course unique stud_id

Revision ID: 0201063dc02c
Revises: 59a3d863dc99
Create Date: 2026-10-07 14:32:17.145894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0201063dc02c'
down_revision: Union[str, Sequence[str], None] = '59a3d863dc99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_course_id_stud_id', ['user_id', 'stud_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('unique_course_id_stud_id', type_='unique')

    # ### end Alembic commands ###
