"""file: add downloaded

Revision ID: 1704c837d5db
Revises: 4f1085385ca8
Create Date: 2026-06-19 10:52:56.365829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1704c837d5db'
down_revision: Union[str, Sequence[str], None] = '4f1085385ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_course_user_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_course_user_id'), ['user_id', 'display_name'])

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downloaded', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('downloaded')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_course_user_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_course_user_id'), ['user_id', 'name'])

    # ### end Alembic commands ###
