"""files: rename display_name to name

Revision ID: 29636a6d1f2a
Revises: 7497eff15f8d
Create Date: 2026-06-16 15:38:26.938188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29636a6d1f2a'
down_revision: Union[str, Sequence[str], None] = '7497eff15f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
