"""add semester model

Revision ID: 2e82bf189b78
Revises: 0201063dc02c
Create Date: 2026-10-09 02:09:09.853530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e82bf189b78'
down_revision: Union[str, Sequence[str], None] = '0201063dc02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stud_id', sa.String(), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_semester_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semester')),
    sa.UniqueConstraint('stud_id', name=op.f('uq_semester_stud_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semester')
    # ### end Alembic commands ###
