"""update after merge

Revision ID: 3ef3e7eb2741
Revises: 3abbe8b66705
Create Date: 2026-05-08 13:19:51.805145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef3e7eb2741'
down_revision: Union[str, Sequence[str], None] = '3abbe8b66705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'announcement', 'course', ['course_id'], ['id'])
    op.add_column('course', sa.Column('cid', sa.String(), nullable=False))
    op.add_column('file', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'file', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'course_id')
    op.drop_column('course', 'cid')
    op.drop_constraint(None, 'announcement', type_='foreignkey')
    op.drop_column('announcement', 'course_id')
    # ### end Alembic commands ###
