"""file: add download_url

Revision ID: 4f1085385ca8
Revises: 584f7b62dcda
Create Date: 2026-06-18 12:53:56.958350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1085385ca8'
down_revision: Union[str, Sequence[str], None] = '584f7b62dcda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_course_user_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_course_user_id'), ['user_id', 'name'])

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('download_url')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_course_user_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_course_user_id'), ['user_id', 'cid'])

    # ### end Alembic commands ###
