"""naming scheme for stud_id

Revision ID: 59a3d863dc99
Revises: e60482d56bc3
Create Date: 2026-10-07 14:30:55.168714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a3d863dc99'
down_revision: Union[str, Sequence[str], None] = 'e60482d56bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_course_id_cid'), type_='unique')
        batch_op.alter_column("cid", new_column_name="stud_id")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stud_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('stud_id')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column("stud_id", new_column_name="cid")
        batch_op.create_unique_constraint(batch_op.f('unique_course_id_cid'), ['user_id', 'cid'])

    # ### end Alembic commands ###
