"""files: make combination of course_id and stud_id

Revision ID: 7497eff15f8d
Revises: 8fc10d2d8a6e
Create Date: 2026-06-16 14:55:29.030026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7497eff15f8d'
down_revision: Union[str, Sequence[str], None] = '8fc10d2d8a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_file_stud_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_file_course_id'), ['course_id', 'stud_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_file_course_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_file_stud_id'), ['stud_id'])

    # ### end Alembic commands ###
