"""update after merge

Revision ID: 7942f31187cb
Revises: 3abbe8b66705
Create Date: 2026-05-08 13:31:30.420465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7942f31187cb'
down_revision: Union[str, Sequence[str], None] = '3abbe8b66705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_announcement_course_id_course'), 'course', ['course_id'], ['id'])

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cid', sa.String(), nullable=False))

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_file_course_id_course'), 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_file_course_id_course'), type_='foreignkey')
        batch_op.drop_column('course_id')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('cid')

    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_announcement_course_id_course'), type_='foreignkey')

    # ### end Alembic commands ###
