"""files: make combination of user_id and cid unique

Revision ID: 8fc10d2d8a6e
Revises: 964abc3acaa8
Create Date: 2026-06-16 14:54:01.528661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc10d2d8a6e'
down_revision: Union[str, Sequence[str], None] = '964abc3acaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_course_user_id'), ['user_id', 'cid'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_course_user_id'), type_='unique')

    # ### end Alembic commands ###
