"""course fix uniqueness

Revision ID: 9197926ba13c
Revises: 1704c837d5db
Create Date: 2026-06-19 10:55:45.302272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9197926ba13c'
down_revision: Union[str, Sequence[str], None] = '1704c837d5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_course_user_id'), type_='unique')
        batch_op.create_unique_constraint('unique_course_id_cid', ['user_id', 'cid'])
        batch_op.create_unique_constraint('unique_course_id_display_name', ['user_id', 'display_name'])
        batch_op.create_unique_constraint('unique_course_id_name', ['user_id', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('unique_course_id_name', type_='unique')
        batch_op.drop_constraint('unique_course_id_display_name', type_='unique')
        batch_op.drop_constraint('unique_course_id_cid', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_course_user_id'), ['user_id', 'display_name'])

    # ### end Alembic commands ###
