"""files: add stud_id and chdate

Revision ID: 964abc3acaa8
Revises: de27b4ca5e4a
Create Date: 2026-06-16 13:29:14.671132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964abc3acaa8'
down_revision: Union[str, Sequence[str], None] = 'de27b4ca5e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stud_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('chdate', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_file_stud_id'), ['stud_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_file_stud_id'), type_='unique')
        batch_op.drop_column('chdate')
        batch_op.drop_column('stud_id')

    # ### end Alembic commands ###
