"""fix course uniqueness

Revision ID: c4dff1ba8133
Revises: 9197926ba13c
Create Date: 2026-10-07 12:22:33.507236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4dff1ba8133'
down_revision: Union[str, Sequence[str], None] = '9197926ba13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_announcement_course_id_course'), 'course', ['course_id'], ['id'])

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_course_id_display_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('unique_course_id_name'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_course_id_name'), ['user_id', 'name'])
        batch_op.create_unique_constraint(batch_op.f('unique_course_id_display_name'), ['user_id', 'display_name'])

    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_announcement_course_id_course'), type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
