"""fix course uniqueness (undo)

Revision ID: e60482d56bc3
Revises: c4dff1ba8133
Create Date: 2026-10-07 13:39:40.852729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e60482d56bc3'
down_revision: Union[str, Sequence[str], None] = 'c4dff1ba8133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_course_id_display_name', ['user_id', 'display_name'])
        batch_op.create_unique_constraint('unique_course_id_name', ['user_id', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('unique_course_id_name', type_='unique')
        batch_op.drop_constraint('unique_course_id_display_name', type_='unique')

    # ### end Alembic commands ###
